server:
  port: 8001

spring:
  datasource:
    platform: series
    driverClassName: org.h2.Driver
    url : jdbc:h2:file:./src/main/resources/static/series
  jpa.hibernate.ddl-auto: update
  application:
    name: series-service