CREATE TABLE IF NOT EXISTS SERIES(ID BIGINT PRIMARY KEY AUTO_INCREMENT,
                  TITLE VARCHAR(30) NOT NULL, DESCRIPTION VARCHAR (255));
CREATE TABLE IF NOT EXISTS EVENTS(ID BIGINT PRIMARY KEY AUTO_INCREMENT, MOMENT BIGINT NOT NULL,
                  DESCRIPTION VARCHAR(255) NOT NULL,TAG VARCHAR(30), SERIEID BIGINT,
                  FOREIGN KEY (SERIEID) REFERENCES SERIES(ID));
CREATE TABLE IF NOT EXISTS  COMMENTS(ID BIGINT PRIMARY KEY AUTO_INCREMENT, TEXT VARCHAR(255) NOT NULL, EVENTID BIGINT,
                FOREIGN KEY (EVENTID) REFERENCES EVENTS(ID));